// @flow
export const
  VIEW_READY:string = 'VIEW_READY',
  RESET_APP:string = 'RESET_APP',
  TOGGLE_INITIAL:string = 'TOGGLE_INITIAL',
  TOGGLE_UPLOAD:string = 'TOGGLE_UPLOAD',
  SELECT_TOPIC:string = 'SELECT_TOPIC',
  SELECT_LANGUAGE:string = 'SELECT_LANGUAGE',
  TOGGLE_LOCATE:string = 'TOGGLE_LOCATE',
  TOGGLE_SHARE:string = 'TOGGLE_SHARE',
  FETCH_ITEM_INFO:string = 'FETCH_ITEM_INFO',
  TOGGLE_BASEMAP:string = 'TOGGLE_BASEMAP',
  TOGGLE_PANEL:string = 'TOGGLE_PANEL';
